def generate_arithmetic_exception():
    a = 10
    b = 0
    print(a/b)

generate_arithmetic_exception()
